### ISSUE TITLE
Wide chars, UTF-8, terminal escapes and colors, etc.

### ISSUE THREAD

**Issue by apjanke** [cowsay-org/cowsay#69]
Cowsay doesn't handle variant character widths well. It kind of assumes all characters are 1 char wide (in display) and (I think) 1 byte (in the input encoding). This means that non-English/Latin characters in the cows or the message text are not handled well.

This is an expansion of [#65 "Use Debian's UTF-8 Patch"](https://github.com/cowsay-org/cowsay/issues/65).

Aspects:

* Messages with multi-byte encoded characters don't look right. The speech balloon width and word wrapping are wrong.
* Terminal control (escape) sequences, like color codes, are treated as visible characters.

Bad-wrapped multi-byte char [example](https://github.com/cowsay-org/cowsay/issues/65):

<img width="373" alt="image" src="https://github.com/user-attachments/assets/603645d4-f9d4-4367-82a8-5b21593a45c1">

## Considerations

The cow files distributed with cowsay are all UTF-8, regardless of what locale the user is running in or how their system is set up. (I think? Or are they actually ASCII/Latin-1, since they are Perl source code?)

Message input might be in the user's locale while the cow files are UTF-8. Custom cows (including in third-party cow herd packages) might be in other encodings, which may or may not be the same encoding as

Perl's standard library doesn't support char width detection, I don't think. Would need a CPAN module for that. We currently don't take any deps on modules. Would need to figure out how to do that. I think we'd vendor the module (ship a copy of it in cowsay itself), to avoid creating any external dependencies or a more complicated install process.

## TODO

* [ ] Determine and document which encoding(s) are supported for cowfiles.
  * [ ] Make our source code UTF-8 (with `use utf8;`)?
* [ ] Add support for detecting, and maybe explicitly setting, message input encoding.
* [ ] Support wide chars and invisible chars (like terminal escapes).
  * ("Wide" in the sense that they are displayed 2-char width; not that they're a `wchar` type in encoding.)

## References

* https://github.com/cowsay-org/cowsay/issues/65
* Third-party patches
  * [Debian patch for UTF-8 input and char sizes](https://sources.debian.org/patches/cowsay/3.03%2Bdfsg2-8/utf8_width/)
* Perl doco
  * [${^UTF8LOCALE}](https://perldoc.perl.org/variables/$%7B%5EUTF8LOCALE%7D)
  * [perlrun -C Unicode features](https://perldoc.perl.org/perlrun#-C-%5Bnumber%2Flist%5D)
  * ["UTF-8 no longer default under UTF-8 locales"](https://perldoc.perl.org/perl581delta#UTF-8-no-longer-default-under-UTF-8-locales)

**Comment by apjanke** [comment]
I [looked in to the licensing some more](https://github.com/cowsay-org/cowsay/issues/68), and I don't think there's actually a licensing problem with the Debian patches or most of their cows. Per their `copyright` file, all their patches (except `cowsay_random`) are licensed under the original Cowsay license terms, so we could pull them in no problem.

Looking at the Debian patch...

```
--- a/cowsay
+++ b/cowsay
@@ -12,6 +12,13 @@ use File::Basename;
 use Getopt::Std;
 use Cwd;
 
+if (${^UTF8LOCALE}) {
+    binmode STDIN, ':utf8';
+    binmode STDOUT, ':utf8';
+    require Encode;
+    eval { $_ = Encode::decode_utf8($_,1) } for @ARGV;
+}
+
 $version = "3.03";
 $progname = basename($0);
```

...hmm. I'm not very familiar with Perl Unicode support.

Looks like this is programmatically doing the equivalent of `perl -C` which enables Unicode-ness and UTF8-ness on file handles and arguments.

Might be able to handle this more gracefully by using `#!/usr/bin/env perl -C` as the shebang. But then it wouldn't work right under explicit `perl cowsay` invocations unless the user explicitly added `-C` or `$PERL_UNICODE` stuff, I think. So maybe this Debian approach is the right way to do it.

See:
* https://perldoc.perl.org/perl581delta#UTF-8-no-longer-default-under-UTF-8-locales
* [perlrun -C Unicode features](https://perldoc.perl.org/perlrun#-C-%5Bnumber%2Flist%5D)

**Comment by apjanke** [comment]
Added support for multibyte UTF-8 chars in inputs in https://github.com/cowsay-org/cowsay/commit/b91f3d2d1935f34397d6a618ac71360ff13cf686, targeted for Cowsay 3.9.0, on the [`dev/free-mime` branch](https://github.com/cowsay-org/cowsay/tree/dev/free-mime) instead of `main`.

Seems to work fine for me:

<img width="976" alt="image" src="https://github.com/user-attachments/assets/0a4ee7ca-ce1d-4b92-9f6d-97883514ac8f">

**Comment by apjanke** [comment]
Oh no, something went rather wrong here.

```
[cowsay] $ cowsay -f sus 'Hello world!'
 ______________
< Hello world! >
 --------------
   \
    \  .ââââââ.
      .âââ.    \
     (     )   +ââ\
      `âââÂ´    |  |
      |        |  |
      |   __   +ââ/
      \__/  \__/
[cowsay] $ git switch main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
[cowsay] $ cowsay -f sus 'Hello world!'
 ______________
< Hello world! >
 --------------
   \
    \  .——————.
      .———.    \
     (     )   +——\
      `———´    |  |
      |        |  |
      |   __   +——/
      \__/  \__/
[cowsay] $
```
<img width="512" alt="image" src="https://github.com/user-attachments/assets/1641b7dc-12d9-4b76-8464-a7f4e6c5d2f6">

**Comment by apjanke** [comment]
Ah. It looks like some of our recent contributions are using non-ASCII UTF-8 characters.

```
[cows] $ pwd
/Users/janke/repos/cowsay-repos/cowsay/share/cowsay/cows
[cows] $ file *
actually.cow:          Unicode text, UTF-8 text
alpaca.cow:            Unicode text, UTF-8 text
beavis.zen.cow:        ASCII text
blowfish.cow:          ASCII text
bong.cow:              ASCII text
[...]
supermilker.cow:       ASCII text
surgery.cow:           ASCII text
sus.cow:               Unicode text, UTF-8 text
three-eyes.cow:        ASCII text
turkey.cow:            ASCII text
```

I don't know what interaction this new "UTF-8 on inputs" is having with cow source files, but seems likely it's something like that.

Maybe the problem is that we're changing STDOUT to UTF8 encoding, and these UTF8-using source files are not marked as UTF8, so they get misinterpreted as single-byte Latin-1 source, converted to chars, and then upon output, Perl renders them as the UTF-8 encoding of that bogus single-byte-encoding interpretation. That'd explain the accented characters: high (8-bit not 7-bit) bytes getting re-rendered.

Maybe `use utf8;` will help.

**Comment by apjanke** [comment]
Trying `use utf8;` in the known UTF-encoded cows.

Before:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/e039edcf-6fab-4594-a8b1-6c6a92382ec2">

After:

<img width="637" alt="image" src="https://github.com/user-attachments/assets/91498353-4f84-4580-a0bd-fb3f17efa468">

Yeah, that looks better.

Did that in https://github.com/cowsay-org/cowsay/commit/fc346f42e8b27d945a7c9c962ad1f47456d33d49.
